import { prisma } from './db'

interface SeedProduct {
  name: string
  brand?: string
  price: number
  priceTier: string
  url: string
  image?: string
  retailer: string
  themes: string[]
  occasions: string[]
  recipients: string[]
  ageRange?: string
  gender?: string
  interests: string[]
  vibes: string[]
}

const CATALOG_PRODUCTS: SeedProduct[] = [
  // ── BUDGET TIER (~$20-35) ──────────────────────────────────
  {
    name: 'Yeti Rambler 20oz Tumbler',
    brand: 'Yeti',
    price: 35,
    priceTier: 'BUDGET',
    url: 'https://www.amazon.com/YETI-Rambler-Tumbler-MagSlider-Stainless/dp/B073WJH2WK',
    retailer: 'Amazon',
    themes: ['practical', 'outdoors'],
    occasions: ['birthday', 'christmas', 'just_because', 'fathers_day'],
    recipients: ['dad', 'friend', 'coworker', 'brother'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['outdoors', 'fitness', 'travel'],
    vibes: ['practical', 'rugged'],
  },
  {
    name: 'Wordle Board Game',
    brand: 'Hasbro',
    price: 20,
    priceTier: 'BUDGET',
    url: 'https://www.amazon.com/Hasbro-Gaming-Wordle-Party-Game/dp/B0B7QXM1TX',
    retailer: 'Amazon',
    themes: ['playful', 'social'],
    occasions: ['christmas', 'birthday', 'housewarming', 'just_because'],
    recipients: ['friend', 'coworker', 'sister', 'mom'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['games', 'puzzles'],
    vibes: ['playful', 'nostalgic'],
  },
  {
    name: 'Rifle Paper Co. 2026 Planner',
    brand: 'Rifle Paper Co.',
    price: 34,
    priceTier: 'BUDGET',
    url: 'https://riflepaperco.com/shop/planners',
    retailer: 'Rifle Paper Co.',
    themes: ['creative', 'organization'],
    occasions: ['christmas', 'just_because', 'graduation'],
    recipients: ['sister', 'friend', 'coworker', 'mom'],
    ageRange: '18-40',
    gender: 'female',
    interests: ['stationery', 'organization', 'art'],
    vibes: ['playful', 'creative'],
  },
  {
    name: 'Baggu Standard Reusable Bag Set',
    brand: 'Baggu',
    price: 36,
    priceTier: 'BUDGET',
    url: 'https://baggu.com/collections/standard-baggu',
    retailer: 'Baggu',
    themes: ['practical', 'eco'],
    occasions: ['just_because', 'housewarming', 'birthday'],
    recipients: ['friend', 'sister', 'mom', 'coworker'],
    ageRange: '18-40',
    gender: 'female',
    interests: ['sustainability', 'fashion'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Litographs Book Scarf',
    brand: 'Litographs',
    price: 32,
    priceTier: 'BUDGET',
    url: 'https://www.litographs.com/collections/scarves',
    retailer: 'Litographs',
    themes: ['literary', 'creative'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['mom', 'sister', 'friend'],
    ageRange: '25-60',
    gender: 'female',
    interests: ['reading', 'fashion', 'literature'],
    vibes: ['creative', 'nostalgic'],
  },
  {
    name: 'Beeswax Food Wrap Set',
    brand: "Bee's Wrap",
    price: 22,
    priceTier: 'BUDGET',
    url: 'https://www.beeswrap.com/collections/all',
    retailer: "Bee's Wrap",
    themes: ['eco', 'kitchen'],
    occasions: ['housewarming', 'christmas', 'just_because'],
    recipients: ['mom', 'friend', 'sister', 'coworker'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'sustainability'],
    vibes: ['practical', 'minimalist'],
  },
  {
    name: 'Uncommon Goods Hand-Stamped Bookmark',
    brand: 'Uncommon Goods',
    price: 28,
    priceTier: 'BUDGET',
    url: 'https://www.uncommongoods.com/product/custom-hand-stamped-bookmark',
    retailer: 'Uncommon Goods',
    themes: ['literary', 'personal'],
    occasions: ['birthday', 'christmas', 'graduation', 'just_because'],
    recipients: ['friend', 'mom', 'sister', 'coworker'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['reading', 'books'],
    vibes: ['nostalgic', 'personal'],
  },
  {
    name: 'Stanley Adventure Quencher 40oz',
    brand: 'Stanley',
    price: 35,
    priceTier: 'BUDGET',
    url: 'https://www.amazon.com/Stanley-Quencher-FlowState-Stainless-Insulated/dp/B0CX57ZC9W',
    retailer: 'Amazon',
    themes: ['practical', 'wellness'],
    occasions: ['birthday', 'christmas', 'just_because'],
    recipients: ['sister', 'friend', 'coworker'],
    ageRange: '18-40',
    gender: 'any',
    interests: ['fitness', 'wellness'],
    vibes: ['practical', 'trendy'],
  },
  {
    name: 'Moleskine Classic Notebook',
    brand: 'Moleskine',
    price: 25,
    priceTier: 'BUDGET',
    url: 'https://www.amazon.com/Moleskine-Classic-Notebook-Large-Ruled/dp/B015NG45Q0',
    retailer: 'Amazon',
    themes: ['creative', 'organization'],
    occasions: ['graduation', 'just_because', 'birthday'],
    recipients: ['friend', 'coworker', 'partner'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['writing', 'journaling', 'stationery'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Brooklinen Luxe Pillowcases (Set of 2)',
    brand: 'Brooklinen',
    price: 35,
    priceTier: 'BUDGET',
    url: 'https://www.brooklinen.com/products/luxe-pillowcases',
    retailer: 'Brooklinen',
    themes: ['cozy', 'home'],
    occasions: ['housewarming', 'birthday', 'just_because'],
    recipients: ['friend', 'sister', 'partner'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['home decor', 'sleep'],
    vibes: ['luxe', 'minimalist'],
  },

  // ── MID TIER (~$40-75) ────────────────────────────────────
  {
    name: 'Hydroflask Wide Mouth 32oz',
    brand: 'Hydroflask',
    price: 45,
    priceTier: 'MID',
    url: 'https://www.amazon.com/Hydro-Flask-Wide-Mouth-Bottle/dp/B01ACAYJ7K',
    retailer: 'Amazon',
    themes: ['practical', 'outdoors', 'wellness'],
    occasions: ['birthday', 'christmas', 'graduation', 'just_because'],
    recipients: ['friend', 'sister', 'brother', 'coworker'],
    ageRange: '18-40',
    gender: 'any',
    interests: ['fitness', 'outdoors', 'hiking'],
    vibes: ['practical', 'trendy'],
  },
  {
    name: 'Uncommon Goods Custom Star Map',
    brand: 'Uncommon Goods',
    price: 50,
    priceTier: 'MID',
    url: 'https://www.uncommongoods.com/product/custom-star-map',
    retailer: 'Uncommon Goods',
    themes: ['personal', 'romantic'],
    occasions: ['anniversary', 'birthday', 'wedding'],
    recipients: ['partner', 'mom', 'dad', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['astronomy', 'art', 'personalized gifts'],
    vibes: ['nostalgic', 'personal'],
  },
  {
    name: 'Birthdate Co. Astrology Candle',
    brand: 'Birthdate Co.',
    price: 48,
    priceTier: 'MID',
    url: 'https://birthdate.co/products/birthdate-candle',
    retailer: 'Birthdate Co.',
    themes: ['personal', 'wellness'],
    occasions: ['birthday', 'just_because'],
    recipients: ['friend', 'sister', 'partner', 'mom'],
    ageRange: '18-40',
    gender: 'female',
    interests: ['astrology', 'self-care'],
    vibes: ['luxe', 'personal'],
  },
  {
    name: 'Aesop Resurrection Hand Balm',
    brand: 'Aesop',
    price: 39,
    priceTier: 'MID',
    url: 'https://www.aesop.com/us/p/body-hand/hand/resurrection-aromatique-hand-balm/',
    retailer: 'Aesop',
    themes: ['wellness', 'beauty'],
    occasions: ['birthday', 'christmas', 'mothers_day', 'just_because'],
    recipients: ['mom', 'sister', 'friend', 'coworker'],
    ageRange: '25-60',
    gender: 'female',
    interests: ['skincare', 'self-care'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'Food52 Five Two Silicone Baking Mats (Set of 2)',
    brand: 'Food52',
    price: 40,
    priceTier: 'MID',
    url: 'https://food52.com/shop/products/7186-silicone-baking-mat',
    retailer: 'Food52',
    themes: ['kitchen', 'foodie'],
    occasions: ['housewarming', 'birthday', 'christmas', 'just_because'],
    recipients: ['mom', 'friend', 'sister'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'baking'],
    vibes: ['practical'],
  },
  {
    name: 'Allbirds Wool Runners',
    brand: 'Allbirds',
    price: 98,
    priceTier: 'MID',
    url: 'https://www.allbirds.com/products/mens-wool-runners',
    retailer: 'Allbirds',
    themes: ['fashion', 'eco'],
    occasions: ['birthday', 'christmas', 'fathers_day', 'just_because'],
    recipients: ['dad', 'partner', 'brother', 'friend'],
    ageRange: '25-60',
    gender: 'male',
    interests: ['fashion', 'sustainability', 'comfort'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Gravity Weighted Blanket 15lb',
    brand: 'Gravity',
    price: 98,
    priceTier: 'MID',
    url: 'https://www.amazon.com/Gravity-Blanket-Weighted-Blanket-Adults/dp/B089GMZNS5',
    retailer: 'Amazon',
    themes: ['cozy', 'wellness'],
    occasions: ['birthday', 'christmas', 'housewarming', 'just_because'],
    recipients: ['partner', 'friend', 'sister', 'mom'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['sleep', 'wellness', 'relaxation'],
    vibes: ['cozy', 'luxe'],
  },
  {
    name: 'Uncommon Goods Personalized Soundwave Art',
    brand: 'Uncommon Goods',
    price: 75,
    priceTier: 'MID',
    url: 'https://www.uncommongoods.com/product/personalized-soundwave-art-print',
    retailer: 'Uncommon Goods',
    themes: ['personal', 'music', 'creative'],
    occasions: ['anniversary', 'birthday', 'wedding'],
    recipients: ['partner', 'friend', 'dad', 'mom'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['music', 'art', 'personalized gifts'],
    vibes: ['nostalgic', 'personal', 'creative'],
  },
  {
    name: 'Our Place Always Pan Mini',
    brand: 'Our Place',
    price: 75,
    priceTier: 'MID',
    url: 'https://fromourplace.com/products/mini-always-pan',
    retailer: 'Our Place',
    themes: ['kitchen', 'foodie'],
    occasions: ['housewarming', 'birthday', 'wedding', 'christmas'],
    recipients: ['friend', 'sister', 'mom'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'MoMA Starry Night Umbrella',
    brand: 'MoMA',
    price: 48,
    priceTier: 'MID',
    url: 'https://store.moma.org/products/starry-night-umbrella',
    retailer: 'MoMA Store',
    themes: ['creative', 'fashion'],
    occasions: ['birthday', 'christmas', 'just_because'],
    recipients: ['mom', 'friend', 'sister'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['art', 'fashion'],
    vibes: ['creative', 'playful'],
  },
  {
    name: 'Patagonia Better Sweater Quarter-Zip',
    brand: 'Patagonia',
    price: 99,
    priceTier: 'MID',
    url: 'https://www.patagonia.com/product/mens-better-sweater-1-4-zip-fleece/25523.html',
    retailer: 'Patagonia',
    themes: ['outdoors', 'fashion', 'eco'],
    occasions: ['birthday', 'christmas', 'fathers_day'],
    recipients: ['dad', 'brother', 'partner', 'friend'],
    ageRange: '25-60',
    gender: 'male',
    interests: ['outdoors', 'hiking', 'sustainability'],
    vibes: ['rugged', 'practical'],
  },
  {
    name: 'Bookshop.org Gift Card',
    brand: 'Bookshop.org',
    price: 50,
    priceTier: 'MID',
    url: 'https://bookshop.org/gift-cards',
    retailer: 'Bookshop.org',
    themes: ['literary'],
    occasions: ['birthday', 'christmas', 'graduation', 'just_because'],
    recipients: ['friend', 'mom', 'sister', 'coworker'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['reading', 'books', 'literature'],
    vibes: ['practical'],
  },
  {
    name: 'Lego Botanical Collection Orchid',
    brand: 'Lego',
    price: 50,
    priceTier: 'MID',
    url: 'https://www.amazon.com/LEGO-Botanical-Collection-10311-Building/dp/B09R4R26DD',
    retailer: 'Amazon',
    themes: ['creative', 'home'],
    occasions: ['birthday', 'christmas', 'housewarming', 'mothers_day'],
    recipients: ['mom', 'friend', 'partner', 'sister'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['art', 'building', 'home decor'],
    vibes: ['playful', 'creative'],
  },
  {
    name: 'Fellow Atmos Vacuum Canister',
    brand: 'Fellow',
    price: 40,
    priceTier: 'MID',
    url: 'https://fellowproducts.com/products/atmos-vacuum-canister',
    retailer: 'Fellow',
    themes: ['kitchen', 'coffee'],
    occasions: ['birthday', 'housewarming', 'christmas', 'just_because'],
    recipients: ['dad', 'friend', 'coworker', 'partner'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['coffee', 'cooking'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Cratejoy Book of the Month Subscription (3 months)',
    brand: 'Book of the Month',
    price: 53,
    priceTier: 'MID',
    url: 'https://www.bookofthemonth.com/gift',
    retailer: 'Book of the Month',
    themes: ['literary', 'subscription'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['friend', 'mom', 'sister'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['reading', 'books'],
    vibes: ['personal'],
  },
  {
    name: 'Caraway Ceramic Baking Sheet',
    brand: 'Caraway',
    price: 45,
    priceTier: 'MID',
    url: 'https://www.carawayhome.com/products/baking-sheet',
    retailer: 'Caraway',
    themes: ['kitchen', 'eco'],
    occasions: ['housewarming', 'birthday', 'wedding'],
    recipients: ['mom', 'friend', 'sister'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'baking'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Sonos Roam 2 Portable Speaker',
    brand: 'Sonos',
    price: 99,
    priceTier: 'MID',
    url: 'https://www.amazon.com/Sonos-Portable-Bluetooth-Speaker-Battery/dp/B0D5C4MNC4',
    retailer: 'Amazon',
    themes: ['tech', 'music'],
    occasions: ['birthday', 'christmas', 'graduation', 'fathers_day'],
    recipients: ['friend', 'brother', 'dad', 'partner'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['music', 'tech'],
    vibes: ['minimalist', 'trendy'],
  },

  // ── PREMIUM TIER (~$100-149) ──────────────────────────────
  {
    name: 'Ember Mug 2 (10oz)',
    brand: 'Ember',
    price: 130,
    priceTier: 'PREMIUM',
    url: 'https://www.amazon.com/Ember-Temperature-Control-Smart-10oz/dp/B07NQRM6ML',
    retailer: 'Amazon',
    themes: ['tech', 'coffee'],
    occasions: ['birthday', 'christmas', 'fathers_day', 'mothers_day'],
    recipients: ['dad', 'mom', 'coworker', 'partner'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['coffee', 'tea', 'tech'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'MasterClass Annual Membership',
    brand: 'MasterClass',
    price: 120,
    priceTier: 'PREMIUM',
    url: 'https://www.masterclass.com/gift',
    retailer: 'MasterClass',
    themes: ['learning', 'creative'],
    occasions: ['birthday', 'christmas', 'graduation', 'just_because'],
    recipients: ['friend', 'dad', 'mom', 'partner'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['learning', 'cooking', 'writing', 'photography'],
    vibes: ['luxe', 'creative'],
  },
  {
    name: 'Kindle Paperwhite (16GB)',
    brand: 'Amazon',
    price: 140,
    priceTier: 'PREMIUM',
    url: 'https://www.amazon.com/Kindle-Paperwhite-16GB-adjustable/dp/B0CFPJYX6F',
    retailer: 'Amazon',
    themes: ['tech', 'literary'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['mom', 'dad', 'partner', 'friend'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['reading', 'books', 'tech'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Le Creuset Stoneware Heritage Rectangular Dish',
    brand: 'Le Creuset',
    price: 100,
    priceTier: 'PREMIUM',
    url: 'https://www.amazon.com/Le-Creuset-Stoneware-Heritage-Rectangular/dp/B00CSWDCB0',
    retailer: 'Amazon',
    themes: ['kitchen', 'foodie'],
    occasions: ['wedding', 'housewarming', 'christmas', 'mothers_day'],
    recipients: ['mom', 'sister', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'baking', 'home decor'],
    vibes: ['luxe', 'practical'],
  },
  {
    name: 'Nike Air Force 1 \'07',
    brand: 'Nike',
    price: 115,
    priceTier: 'PREMIUM',
    url: 'https://www.nike.com/t/air-force-1-07-shoes-WrLlWX',
    retailer: 'Nike',
    themes: ['fashion'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['brother', 'friend', 'partner'],
    ageRange: '18-25',
    gender: 'any',
    interests: ['fashion', 'sneakers'],
    vibes: ['trendy'],
  },
  {
    name: 'Therabody Wave Roller',
    brand: 'Therabody',
    price: 99,
    priceTier: 'PREMIUM',
    url: 'https://www.therabody.com/us/en-us/wave-roller.html',
    retailer: 'Therabody',
    themes: ['wellness', 'fitness'],
    occasions: ['birthday', 'christmas', 'just_because'],
    recipients: ['friend', 'partner', 'dad', 'brother'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['fitness', 'wellness', 'running'],
    vibes: ['practical'],
  },
  {
    name: 'Staub Ceramic Baking Dish Set',
    brand: 'Staub',
    price: 100,
    priceTier: 'PREMIUM',
    url: 'https://www.amazon.com/Staub-Ceramics-Rectangular-Baking-Cherry/dp/B003I9U3E0',
    retailer: 'Amazon',
    themes: ['kitchen', 'foodie'],
    occasions: ['wedding', 'housewarming', 'christmas'],
    recipients: ['mom', 'friend', 'sister'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'baking'],
    vibes: ['luxe', 'practical'],
  },
  {
    name: 'Casper Glow Light',
    brand: 'Casper',
    price: 129,
    priceTier: 'PREMIUM',
    url: 'https://casper.com/glow-light/',
    retailer: 'Casper',
    themes: ['cozy', 'tech', 'wellness'],
    occasions: ['housewarming', 'birthday', 'christmas'],
    recipients: ['partner', 'friend', 'mom'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['sleep', 'wellness', 'tech'],
    vibes: ['minimalist', 'cozy'],
  },
  {
    name: 'Ray-Ban New Wayfarer Sunglasses',
    brand: 'Ray-Ban',
    price: 140,
    priceTier: 'PREMIUM',
    url: 'https://www.amazon.com/Ray-Ban-RB2132-Wayfarer-Sunglasses/dp/B001UQ71G4',
    retailer: 'Amazon',
    themes: ['fashion'],
    occasions: ['birthday', 'graduation', 'just_because'],
    recipients: ['partner', 'friend', 'brother', 'sister'],
    ageRange: '18-40',
    gender: 'any',
    interests: ['fashion', 'travel'],
    vibes: ['trendy', 'luxe'],
  },
  {
    name: 'Our Place Always Pan 2.0',
    brand: 'Our Place',
    price: 130,
    priceTier: 'PREMIUM',
    url: 'https://fromourplace.com/products/always-pan',
    retailer: 'Our Place',
    themes: ['kitchen', 'foodie'],
    occasions: ['wedding', 'housewarming', 'birthday', 'christmas'],
    recipients: ['friend', 'sister', 'mom'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking'],
    vibes: ['minimalist', 'practical'],
  },
  {
    name: 'Lululemon Everywhere Belt Bag',
    brand: 'Lululemon',
    price: 38,
    priceTier: 'MID',
    url: 'https://shop.lululemon.com/p/bags/Everywhere-Belt-Bag/_/prod8900747',
    retailer: 'Lululemon',
    themes: ['fashion', 'fitness'],
    occasions: ['birthday', 'christmas', 'just_because'],
    recipients: ['sister', 'friend'],
    ageRange: '18-40',
    gender: 'female',
    interests: ['fitness', 'fashion', 'travel'],
    vibes: ['trendy', 'practical'],
  },

  // ── LUXURY TIER ($150+) ───────────────────────────────────
  {
    name: 'Theragun Mini (2nd Gen)',
    brand: 'Therabody',
    price: 199,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Therabody-Theragun-mini-2nd-Gen/dp/B0C9PF12K3',
    retailer: 'Amazon',
    themes: ['wellness', 'fitness', 'tech'],
    occasions: ['birthday', 'christmas', 'fathers_day'],
    recipients: ['dad', 'partner', 'friend', 'brother'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['fitness', 'wellness', 'running'],
    vibes: ['luxe', 'practical'],
  },
  {
    name: 'Bose QuietComfort Ultra Earbuds',
    brand: 'Bose',
    price: 179,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Bose-QuietComfort-Wireless-Cancelling-Earbuds/dp/B0CD2FSRDD',
    retailer: 'Amazon',
    themes: ['tech', 'music'],
    occasions: ['birthday', 'christmas', 'graduation', 'fathers_day'],
    recipients: ['partner', 'dad', 'friend', 'brother'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['music', 'tech', 'travel'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'Apple AirPods Pro (2nd Gen)',
    brand: 'Apple',
    price: 249,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Apple-Generation-Cancelling-Transparency-Personalized/dp/B0D1XD1ZV3',
    retailer: 'Amazon',
    themes: ['tech', 'music'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['partner', 'friend', 'brother', 'sister'],
    ageRange: '18-40',
    gender: 'any',
    interests: ['music', 'tech', 'podcasts'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'Dyson Airwrap Multi-Styler',
    brand: 'Dyson',
    price: 600,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Dyson-Airwrap-Multi-Styler-Complete/dp/B0BNK7GLP2',
    retailer: 'Amazon',
    themes: ['beauty', 'tech'],
    occasions: ['birthday', 'christmas', 'mothers_day'],
    recipients: ['partner', 'sister', 'mom'],
    ageRange: '18-60',
    gender: 'female',
    interests: ['beauty', 'hair care'],
    vibes: ['luxe'],
  },
  {
    name: 'Vitamix Explorian Blender E310',
    brand: 'Vitamix',
    price: 290,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Vitamix-Explorian-Professional-Grade-Container-Black/dp/B0758JHZM3',
    retailer: 'Amazon',
    themes: ['kitchen', 'foodie', 'wellness'],
    occasions: ['wedding', 'housewarming', 'birthday', 'christmas'],
    recipients: ['mom', 'partner', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['cooking', 'wellness', 'smoothies'],
    vibes: ['practical', 'luxe'],
  },
  {
    name: 'Apple Watch SE (2nd Gen)',
    brand: 'Apple',
    price: 249,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Apple-Smartwatch-Midnight-Aluminum-Detection/dp/B0CHX7R6WJ',
    retailer: 'Amazon',
    themes: ['tech', 'fitness', 'wellness'],
    occasions: ['birthday', 'christmas', 'graduation'],
    recipients: ['partner', 'friend', 'brother', 'sister'],
    ageRange: '18-40',
    gender: 'any',
    interests: ['fitness', 'tech', 'wellness'],
    vibes: ['luxe', 'trendy'],
  },
  {
    name: 'Dyson V8 Cordless Vacuum',
    brand: 'Dyson',
    price: 350,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Dyson-Cordless-Vacuum-Cleaner-Silver/dp/B0B54DP54V',
    retailer: 'Amazon',
    themes: ['home', 'practical', 'tech'],
    occasions: ['housewarming', 'wedding', 'christmas'],
    recipients: ['partner', 'mom', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['home', 'cleaning', 'tech'],
    vibes: ['practical', 'luxe'],
  },
  {
    name: 'Oura Ring Gen 3',
    brand: 'Oura',
    price: 299,
    priceTier: 'LUXURY',
    url: 'https://ouraring.com/product/rings',
    retailer: 'Oura',
    themes: ['tech', 'wellness', 'fitness'],
    occasions: ['birthday', 'christmas', 'anniversary'],
    recipients: ['partner', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['fitness', 'wellness', 'tech', 'sleep'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'Away Carry-On Suitcase',
    brand: 'Away',
    price: 275,
    priceTier: 'LUXURY',
    url: 'https://www.awaytravel.com/suitcases/carry-on',
    retailer: 'Away',
    themes: ['travel'],
    occasions: ['birthday', 'graduation', 'christmas'],
    recipients: ['partner', 'friend', 'sister', 'brother'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['travel'],
    vibes: ['minimalist', 'luxe'],
  },
  {
    name: 'Breville Barista Express Espresso Machine',
    brand: 'Breville',
    price: 600,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Breville-BES870XL-Barista-Express-Espresso/dp/B00CH9QWOU',
    retailer: 'Amazon',
    themes: ['kitchen', 'coffee', 'tech'],
    occasions: ['wedding', 'housewarming', 'birthday', 'christmas', 'anniversary'],
    recipients: ['partner', 'dad', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['coffee', 'cooking'],
    vibes: ['luxe', 'practical'],
  },
  {
    name: 'Bose SoundLink Max Portable Speaker',
    brand: 'Bose',
    price: 399,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Bose-SoundLink-Bluetooth-Portable-Waterproof/dp/B0D7S6G2LB',
    retailer: 'Amazon',
    themes: ['tech', 'music', 'outdoors'],
    occasions: ['birthday', 'christmas', 'graduation', 'fathers_day'],
    recipients: ['dad', 'partner', 'friend', 'brother'],
    ageRange: '18-60',
    gender: 'any',
    interests: ['music', 'tech', 'outdoors'],
    vibes: ['luxe'],
  },
  {
    name: 'KitchenAid Artisan Stand Mixer',
    brand: 'KitchenAid',
    price: 380,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/KitchenAid-KSM150PSER-Artisan-Pouring-Shield/dp/B00005UP2P',
    retailer: 'Amazon',
    themes: ['kitchen', 'foodie'],
    occasions: ['wedding', 'birthday', 'christmas', 'housewarming'],
    recipients: ['mom', 'partner', 'sister', 'friend'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['baking', 'cooking'],
    vibes: ['luxe', 'practical'],
  },
  {
    name: 'Aesop Aromatique Hand Wash & Balm Duet',
    brand: 'Aesop',
    price: 153,
    priceTier: 'LUXURY',
    url: 'https://www.aesop.com/us/p/body-hand/hand/resurrection-aromatique-hand-wash-and-hand-balm-duet/',
    retailer: 'Aesop',
    themes: ['beauty', 'wellness'],
    occasions: ['birthday', 'mothers_day', 'christmas', 'housewarming'],
    recipients: ['mom', 'sister', 'friend'],
    ageRange: '25-60',
    gender: 'female',
    interests: ['skincare', 'self-care'],
    vibes: ['luxe', 'minimalist'],
  },
  {
    name: 'Bang & Olufsen Beoplay EX Earbuds',
    brand: 'Bang & Olufsen',
    price: 399,
    priceTier: 'LUXURY',
    url: 'https://www.amazon.com/Bang-Olufsen-Beoplay-Adaptive-Cancellation/dp/B09Y9S8W1Z',
    retailer: 'Amazon',
    themes: ['tech', 'music'],
    occasions: ['birthday', 'christmas', 'anniversary'],
    recipients: ['partner', 'dad'],
    ageRange: '25-60',
    gender: 'any',
    interests: ['music', 'tech', 'audiophile'],
    vibes: ['luxe', 'minimalist'],
  },
]

/**
 * Seed the catalog with curated products.
 * Idempotent — skips products that already exist by name.
 */
export async function seedCatalog(): Promise<{ created: number; skipped: number }> {
  let created = 0
  let skipped = 0

  for (const product of CATALOG_PRODUCTS) {
    const existing = await prisma.catalogProduct.findFirst({
      where: { name: product.name },
    })

    if (existing) {
      skipped++
      continue
    }

    await prisma.catalogProduct.create({
      data: {
        name: product.name,
        brand: product.brand || null,
        price: product.price,
        priceTier: product.priceTier,
        url: product.url,
        image: product.image || null,
        retailer: product.retailer,
        themes: product.themes,
        occasions: product.occasions,
        recipients: product.recipients,
        ageRange: product.ageRange || null,
        gender: product.gender || null,
        interests: product.interests,
        vibes: product.vibes,
      },
    })
    created++
  }

  return { created, skipped }
}
