export const dummyItems = [
  {
    id: 'dummy-1',
    name: 'AirPods Max',
    price: '$549.00',
    priceValue: 549,
    image: 'https://picsum.photos/400/500?random=1',
    url: 'https://apple.com/airpods-max',
    domain: 'apple.com',
    category: 'Electronics',
    source: 'EXTENSION',
    fundedAmount: 200,
    goalAmount: 549,
    isPurchased: false,
  },
  {
    id: 'dummy-2',
    name: 'Aesop Resurrection Hand Cream',
    price: '$39.00',
    priceValue: 39,
    image: 'https://picsum.photos/400/500?random=2',
    url: 'https://aesop.com/hand-cream',
    domain: 'aesop.com',
    category: 'Beauty',
    source: 'WHATSAPP',
    fundedAmount: 0,
    goalAmount: 39,
    isPurchased: false,
  },
  {
    id: 'dummy-3',
    name: 'Stanley Quencher Tumbler 40oz',
    price: '$45.00',
    priceValue: 45,
    image: 'https://picsum.photos/400/500?random=3',
    url: 'https://stanley1913.com/tumbler',
    domain: 'stanley1913.com',
    category: 'Kitchen',
    source: 'EXTENSION',
    fundedAmount: 45,
    goalAmount: 45,
    isPurchased: false,
  },
  {
    id: 'dummy-4',
    name: 'LEGO Botanical Collection Orchid',
    price: '$49.99',
    priceValue: 49.99,
    image: 'https://picsum.photos/400/500?random=4',
    url: 'https://lego.com/orchid',
    domain: 'lego.com',
    category: 'Toys',
    source: 'MANUAL',
    fundedAmount: 0,
    goalAmount: 49.99,
    isPurchased: false,
  },
  {
    id: 'dummy-5',
    name: 'Nike Dunk Low Retro',
    price: '$115.00',
    priceValue: 115,
    image: 'https://picsum.photos/400/500?random=5',
    url: 'https://nike.com/dunk-low',
    domain: 'nike.com',
    category: 'Fashion',
    source: 'EXTENSION',
    fundedAmount: 50,
    goalAmount: 115,
    isPurchased: false,
  },
  {
    id: 'dummy-6',
    name: 'Kindle Paperwhite Signature Edition',
    price: '$189.99',
    priceValue: 189.99,
    image: 'https://picsum.photos/400/500?random=6',
    url: 'https://amazon.com/kindle-paperwhite',
    domain: 'amazon.com',
    category: 'Electronics',
    source: 'WHATSAPP',
    fundedAmount: 0,
    goalAmount: 189.99,
    isPurchased: false,
  },
  {
    id: 'dummy-7',
    name: 'Le Creuset Dutch Oven 5.5qt',
    price: '$419.95',
    priceValue: 419.95,
    image: 'https://picsum.photos/400/500?random=7',
    url: 'https://lecreuset.com/dutch-oven',
    domain: 'lecreuset.com',
    category: 'Kitchen',
    source: 'EXTENSION',
    fundedAmount: 150,
    goalAmount: 419.95,
    isPurchased: false,
  },
  {
    id: 'dummy-8',
    name: 'Dyson Airwrap Multi-Styler',
    price: '$599.99',
    priceValue: 599.99,
    image: 'https://picsum.photos/400/500?random=8',
    url: 'https://dyson.com/airwrap',
    domain: 'dyson.com',
    category: 'Beauty',
    source: 'WHATSAPP',
    fundedAmount: 300,
    goalAmount: 599.99,
    isPurchased: false,
  },
]

export const dummyActivities = [
  {
    id: 'act-1',
    type: 'ITEM_ADDED',
    userName: 'Sarah Chen',
    action: 'added AirPods Max to their wishlist',
    emoji: '\u{1F3A7}',
    amount: null,
    timeAgo: '2m ago',
  },
  {
    id: 'act-2',
    type: 'ITEM_FUNDED',
    userName: 'Mike Johnson',
    action: 'funded Stanley Tumbler',
    emoji: '\u{1F4B0}',
    amount: 45,
    timeAgo: '15m ago',
  },
  {
    id: 'act-3',
    type: 'CONTRIBUTION_RECEIVED',
    userName: 'Emma Wilson',
    action: 'contributed to Nike Dunks',
    emoji: '\u{1F381}',
    amount: 50,
    timeAgo: '1h ago',
  },
  {
    id: 'act-4',
    type: 'EVENT_CREATED',
    userName: 'Alex Rivera',
    action: 'created "Birthday Bash 2026"',
    emoji: '\u{1F389}',
    amount: null,
    timeAgo: '2h ago',
  },
  {
    id: 'act-5',
    type: 'ITEM_ADDED',
    userName: 'Jordan Lee',
    action: 'added Dyson Airwrap to their wishlist',
    emoji: '\u{2728}',
    amount: null,
    timeAgo: '3h ago',
  },
  {
    id: 'act-6',
    type: 'ITEM_FUNDED',
    userName: 'Taylor Kim',
    action: 'funded Le Creuset Dutch Oven',
    emoji: '\u{1F4B0}',
    amount: 150,
    timeAgo: '5h ago',
  },
  {
    id: 'act-7',
    type: 'CONTRIBUTION_RECEIVED',
    userName: 'Chris Patel',
    action: 'contributed to Kindle Paperwhite',
    emoji: '\u{1F381}',
    amount: 75,
    timeAgo: '8h ago',
  },
  {
    id: 'act-8',
    type: 'ITEM_ADDED',
    userName: 'Sam Garcia',
    action: 'added LEGO Orchid to their wishlist',
    emoji: '\u{1F33A}',
    amount: null,
    timeAgo: '1d ago',
  },
]
