// Short slug → pre-filled WhatsApp prompt mapping for seasonal holiday links
// Used by /c/[slug] route and holiday message generation

export const holidaySlugs: Record<string, string> = {
  'new-year': "Happy New Year! I'm looking for a gift for someone who made last year special",
  'mlk-day': "I need a gift idea for a teacher or community leader for MLK Day",
  'galentines': "I need a last-minute Galentine's Day gift for my best friend",
  'valentines': "Help me find the perfect Valentine's Day gift for my partner",
  'lunar-new-year': "I need Lunar New Year gift ideas for my family",
  'womens-day': "I'm looking for a thoughtful gift for an important woman in my life",
  'st-patricks': "I need a host gift for a St. Patrick's Day party",
  'easter': "I need Easter gift ideas — baskets, host gifts, or something for family",
  'earth-day': "I'm looking for eco-friendly or sustainable gift ideas for Earth Day",
  'admin-day': "I need a thank-you gift for an administrative professional at work",
  'mothers-day': "Help me find the perfect Mother's Day gift — not a candle!",
  'cinco-de-mayo': "I need host gift ideas for a Cinco de Mayo celebration",
  'teacher': "I need a gift for my kid's teacher for Teacher Appreciation Week",
  'fathers-day': "Help me find the perfect Father's Day gift — tell me what he's into",
  'juneteenth': "I'm looking for meaningful Juneteenth gift ideas or Black-owned businesses",
  'graduation': "I need a great graduation gift — what do you recommend?",
  'july-4th': "I need host gifts or party essentials for a 4th of July cookout",
  'back-to-school': "I need back-to-school gift ideas for a student or teacher",
  'friendship-day': "I want to surprise my best friend with something for Friendship Day",
  'labor-day': "I want to thank a hardworking person in my life for Labor Day",
  'grandparents-day': "I need a special gift for my grandparent for Grandparents' Day",
  'boss-day': "I need a tasteful Boss's Day gift — or help organizing a group gift",
  'sweetest-day': "I want to surprise my partner with something sweet for Sweetest Day",
  'halloween': "I need Halloween gift ideas — costumes, party stuff, or trick-or-treat goodies",
  'veterans-day': "I need a meaningful gift for a veteran or service member",
  'thanksgiving': "I need Thanksgiving host gifts or friendsgiving ideas",
  'black-friday': "Help me find the best Black Friday deals for gifts on my wishlist",
  'christmas': "Help me find Christmas gift ideas — who should I shop for first?",
  'nye': "I need host gifts or party ideas for New Year's Eve",
  'secret-santa': "I need Secret Santa gift ideas under $25 — tell me about the person",
}

// Reverse lookup: get slug for a holiday name
export function getSlugForHoliday(holidayName: string): string | undefined {
  const nameToSlug: Record<string, string> = {
    "New Year's Day": 'new-year',
    'MLK Day': 'mlk-day',
    "Galentine's Day": 'galentines',
    "Valentine's Day": 'valentines',
    'Lunar New Year': 'lunar-new-year',
    "International Women's Day": 'womens-day',
    "St. Patrick's Day": 'st-patricks',
    'Easter': 'easter',
    'Earth Day': 'earth-day',
    'Admin Professionals Day': 'admin-day',
    "Mother's Day": 'mothers-day',
    'Cinco de Mayo': 'cinco-de-mayo',
    'Teacher Appreciation': 'teacher',
    "Father's Day": 'fathers-day',
    'Juneteenth': 'juneteenth',
    'Graduation Season': 'graduation',
    'Independence Day': 'july-4th',
    'Back to School': 'back-to-school',
    'Friendship Day': 'friendship-day',
    'Labor Day': 'labor-day',
    "Grandparents' Day": 'grandparents-day',
    "Boss's Day": 'boss-day',
    'Sweetest Day': 'sweetest-day',
    'Halloween': 'halloween',
    'Veterans Day': 'veterans-day',
    'Thanksgiving': 'thanksgiving',
    'Black Friday': 'black-friday',
    'Christmas': 'christmas',
    "New Year's Eve": 'nye',
    'Secret Santa Season': 'secret-santa',
  }
  return nameToSlug[holidayName]
}
